image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:

 script:
  - apk add git
  - git submodule add -f https://gitlab.com/kskarthik/monopriv themes/monopriv
  - hugo
 artifacts:
    paths:
    - public
 only:
    - main


