baseURL = "https://_pierluigi.gitlab.io/wedding/"
title = "Pierluigi & Sara si sposano!"
languagecode = "en"
author = "Steve Francia"
# copyright = "Copyright © 2008–2019" #supports html markup
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-123-45"
disqusShortname = "yourdiscussshortname"
theme = "monopriv"
enableEmoji = true
summaryLength = 20

[params]  
    mainSections = ["post"]
    intro = true
    about = ""
    paypalme = "https://paypal.me/pierpuce?country.x=IT&locale.x=it_IT"
    gitlab = "https://gitlab.com/_pierluigi/wedding"
    email = "pierluigi.puce@protonmail.com"
    # site meta description
    metadesc = "monopriv - A simple privacy oriented bootstrap hugo blog"
    # site meta keywords
    metakeys = "hugo, simple, minimal, bootstrap, blog"
    # enable/disable disqus comments 
    disqus = false 
    # enable/disable google analytics 
    analytics = false

[Permalinks]
    post = "/:filename/"

[params.search] # Site search powered by DuckDuckGo
    enabled = false
    placeholder="Site Search"

[params.hero]
    enabled = true
    img = "img/logo.png"
